#!/bin/bash
echo "=== GitHub Repository Status Check ==="
echo ""
echo "Repository: https://github.com/ianmoran11/openstockflow"
echo ""
echo "Please check the following:"
echo ""
echo "1. GitHub Actions Status:"
echo "   Visit: https://github.com/ianmoran11/openstockflow/actions"
echo "   - Look for 'pkgdown' workflow"
echo "   - It should show a green checkmark when complete"
echo ""
echo "2. Check if gh-pages branch exists:"
echo "   Visit: https://github.com/ianmoran11/openstockflow/branches"
echo "   - The 'pkgdown' workflow creates this branch"
echo ""
echo "3. Configure GitHub Pages:"
echo "   Visit: https://github.com/ianmoran11/openstockflow/settings/pages"
echo "   - Source: Deploy from a branch"
echo "   - Branch: gh-pages"
echo "   - Folder: / (root)"
echo "   - Click Save"
echo ""
echo "4. Your website will be at:"
echo "   https://ianmoran11.github.io/openstockflow/"
echo ""
